# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Imane BENOMAR
tagline:          'Portfolio'
url:              https://dg.github.io/

author:
  name:           'Imane BENOMAR'
  github:         imanebenomar
  linkedin:       imanebenomar

paginate:         5

# Custom vars
version:          2.1.0

plugins: 
  - jekyll-paginate
  - jekyll-gist
  

